const products = [
    {name: 'Strawberry Sugar Scrub', price: 15.00, image: 'strawberry.png', description: 'A gentle vegan lip scrub that cleanses, exfoliates, and conditions the lips with natural organic ingredients. Try the new mango flavour. \n A gentle lip scrub that cleanses, exfoliates, and conditions, leaving lips incredibly soft, smooth, and hydrated. It gently buffs away dry flakes with sugar crystals and natural humectants, while conditioning chapped lips with Shea butter and Jojoba oil, leaving them incredibly soft, smooth, and ready for lipstick application. The lip scrub is the perfect prep step to incorporate into any lip ritual for the sweetest, softest lips. This Gluten-free, Vegan lip scrub infused with Coconut oil, Avocado oil, Vitamin E which leaves your lips feeling soft and super supple and creates luscious, kissable lips.'},
    {name: 'Vintage Rose', price: 20.00, image: 'vintage.png', description: 'A paraben-free lipstick with a formula that lasts all day and nourishes the lips with it\'s natural ingredients such as avocado oil and natural beeswax.\nThis high-coverage lip stain provides a beautiful long-lasting color. The creamy texture adds a silky lightweight stain specifically formulated for comfort. The paraben-free formula with added vitamin E ensures your lips feel soft, moisturized and comfortable.'},
    {name: 'Medium BB', price: 20.00, image: 'mediumbb.png', description: 'Our BB cream combines the core benefits from a nourishing skincare routine with the practically of smoothing out your skin tone that acts a lightweight oil-controlling foundation. It\'s easy to apply and can be used by anyone regardless of their skincare routines.\n The cream is light-weight, protects your skin against damaging UV rays, smooths uneven skin, and is formulates with high levels of active skincare ingredients to maintain your skin\'s health. The multi-peptide complex is a chain of amino acids that reduce the appearance of fine lines on your skin by promoting the formulation of healthy new collagens that provides the growth of connective tissue. Chamomile is added as an essential oils that are anti-allergenic and anti-inflammatory to heal dry skin. Vitamin A and Vitamin E are added to retain moisture to keep your face feeling moisturized. All these benefits hide any skin imperfections without clogging any pores.'},
    {name: 'Water based primer', price: 30.00, image: 'water.png', description: 'Silicon-free primer for makeup application to smooth out skin and provide a canvas for makeup application.\n This lightweight, water based primer that transforms your face into a flawless and smooth canvas and enhances the skin’s texture and primes the skin for makeup application. Promotes long-lasting makeup and controls oil and shine, creates a protective layer on the skin allowing foundation to glide on evenly and last longer. Oil-free, Silicone-free, Suitable for all skin types.'},
    {name: 'Lavish Deep Cleaning Mask', price: 25.00, image: 'mask.png', description: 'Waterproof gel that\'s long-lasting, paraben-free and fragrance-free.\nThis waterproof and long-lasting formula will not crease or smudge because of its impeccable hold. The eyeliner glides on smoothly and provides immediate color intensity with a luminous finish. Creamy textures allow a quick application with a brush. The formula is paraben-free and fragrance-free.'},
    {name: 'Bodied by Lavish', price: 20.00, image: 'bodied.png', description: 'This botanically rich and non-greasy lotion restore skin’s elasticity and hydration.\nThis botanically rich and non-greasy, Hand and Body Lotion absorbs quickly to restore skin’s elasticity and delivers deep, long-lasting hydration and calms irritated skin. It is ideal for replenishing lost moisture and restoring the skin’s soft, silky feel. Highly concentrated, soothing Aloe Vera instantly relieves discomforts of dry, irritated, sun-damaged skin. This lotion is excellent for the face, hands, and body, helping to counteract the effects of pollution and the environment. With use, the skin is calmed, balanced, and nurtured back to its healthy-looking best.'},
    {name: 'Brown Beauty', price: 25.00, image: 'brown.png', description: 'Talc-free eyeshadows that are formulated with creamy textures for high-pigmentation and soft natural looks.\nA unique talc-free shadow with a silky, creamy texture formulated for maximum color impact. Blends effortlessly, buildable and provide soft natural look. Highly pigmented, crease resistant and finishes beautifully and naturally. The softly shimmering shades provide immediate color intensity with luminous finish and appeal light effects.'},
    {name: 'Black Eyeliner', price: 20.00, image: 'black.png', description: 'Waterproof gel that\'s long-lasting, paraben-free and fragrance-free.\nThis waterproof and long-lasting formula will not crease or smudge because of its impeccable hold. The eyeliner glides on smoothly and provides immediate color intensity with a luminous finish. Creamy textures allow a quick application with a brush. The formula is paraben-free and fragrance-free.'},
]

export default function (req, res) {
    res.status(200).json(products);
}